# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cdc7a5cd61bcf8bb52a5cf7c8bc3642b3d8aa359dc557c03288cc5a647c34666d9c750ca53b579d7cb91538a0186ffed4e0b51a806648d0e3f1d6ecd59aed02

test:
  secret_key_base: 3ead192895698ea5bfe0ff67e9aedae4dea1ec1233987dae3d2c8e3a9b5553ceee68b2cab19821ebb92c56ed74b8265495ebd225230e171dc234226cb1ab167b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
